//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 06:47:32 PM CST 
//


package com.budgetprepay.verizon.rss.pojos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				MPNPoolName added in release 2040:
 * 				If the MPNPoolName tag is given in the xml, the feature element
 * 			for MPN static IP or MPN dynamic IP (MPNSIP or MPNDIP) should
 * 			be included in the  features section.
 * 			
 * 
 * <p>Java class for resellerChangeRatePlanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resellerChangeRatePlanType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.verizonwireless.com/oas}resellerSubOrderBaseType">
 *       &lt;sequence>
 *         &lt;element name="min" type="{http://www.verizonwireless.com/oas}minType" minOccurs="0"/>
 *         &lt;element name="mdn" type="{http://www.verizonwireless.com/oas}mdnType"/>
 *         &lt;element name="esn" type="{http://www.verizonwireless.com/oas}esnType" minOccurs="0"/>
 *         &lt;element name="meid" type="{http://www.verizonwireless.com/oas}meidType" minOccurs="0"/>
 *         &lt;element name="newIccid" type="{http://www.verizonwireless.com/oas}SIMCardType" minOccurs="0"/>
 *         &lt;element name="newEsn" type="{http://www.verizonwireless.com/oas}esnType" minOccurs="0"/>
 *         &lt;element name="newMeid" type="{http://www.verizonwireless.com/oas}meidType" minOccurs="0"/>
 *         &lt;element name="mobileIPAddress" type="{http://www.verizonwireless.com/oas}oasStringType" minOccurs="0"/>
 *         &lt;element name="MPNPoolName" type="{http://www.verizonwireless.com/oas}oasStringType" minOccurs="0"/>
 *         &lt;element name="SubOrgID" type="{http://www.verizonwireless.com/oas}oasStringType" minOccurs="0"/>
 *         &lt;element name="FUSFExemptFlag" type="{http://www.verizonwireless.com/oas}yesNoType" minOccurs="0"/>
 *         &lt;element name="globalSIMCard" type="{http://www.verizonwireless.com/oas}globalSIMCardType" minOccurs="0"/>
 *         &lt;element name="serviceTypeChange" type="{http://www.verizonwireless.com/oas}yesNoType" minOccurs="0"/>
 *         &lt;element name="newRatePlan" type="{http://www.verizonwireless.com/oas}ratePlanType"/>
 *         &lt;element name="oldRatePlan" type="{http://www.verizonwireless.com/oas}ratePlanType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resellerChangeRatePlanType", propOrder = {
    "min",
    "mdn",
    "esn",
    "meid",
    "newIccid",
    "newEsn",
    "newMeid",
    "mobileIPAddress",
    "mpnPoolName",
    "subOrgID",
    "fusfExemptFlag",
    "globalSIMCard",
    "serviceTypeChange",
    "newRatePlan",
    "oldRatePlan"
})
public class ResellerChangeRatePlanType
    extends ResellerSubOrderBaseType
{

    protected String min;
    @XmlElement(required = true)
    protected MdnType mdn;
    protected String esn;
    protected String meid;
    protected String newIccid;
    protected String newEsn;
    protected String newMeid;
    protected OasStringType mobileIPAddress;
    @XmlElement(name = "MPNPoolName")
    protected OasStringType mpnPoolName;
    @XmlElement(name = "SubOrgID")
    protected OasStringType subOrgID;
    @XmlElement(name = "FUSFExemptFlag")
    protected YesNoType fusfExemptFlag;
    protected String globalSIMCard;
    protected YesNoType serviceTypeChange;
    @XmlElement(required = true)
    protected RatePlanType newRatePlan;
    @XmlElement(required = true)
    protected RatePlanType oldRatePlan;

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMin(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link MdnType }
     *     
     */
    public MdnType getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MdnType }
     *     
     */
    public void setMdn(MdnType value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the esn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsn() {
        return esn;
    }

    /**
     * Sets the value of the esn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsn(String value) {
        this.esn = value;
    }

    /**
     * Gets the value of the meid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeid() {
        return meid;
    }

    /**
     * Sets the value of the meid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeid(String value) {
        this.meid = value;
    }

    /**
     * Gets the value of the newIccid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewIccid() {
        return newIccid;
    }

    /**
     * Sets the value of the newIccid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewIccid(String value) {
        this.newIccid = value;
    }

    /**
     * Gets the value of the newEsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewEsn() {
        return newEsn;
    }

    /**
     * Sets the value of the newEsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewEsn(String value) {
        this.newEsn = value;
    }

    /**
     * Gets the value of the newMeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewMeid() {
        return newMeid;
    }

    /**
     * Sets the value of the newMeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewMeid(String value) {
        this.newMeid = value;
    }

    /**
     * Gets the value of the mobileIPAddress property.
     * 
     * @return
     *     possible object is
     *     {@link OasStringType }
     *     
     */
    public OasStringType getMobileIPAddress() {
        return mobileIPAddress;
    }

    /**
     * Sets the value of the mobileIPAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasStringType }
     *     
     */
    public void setMobileIPAddress(OasStringType value) {
        this.mobileIPAddress = value;
    }

    /**
     * Gets the value of the mpnPoolName property.
     * 
     * @return
     *     possible object is
     *     {@link OasStringType }
     *     
     */
    public OasStringType getMPNPoolName() {
        return mpnPoolName;
    }

    /**
     * Sets the value of the mpnPoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasStringType }
     *     
     */
    public void setMPNPoolName(OasStringType value) {
        this.mpnPoolName = value;
    }

    /**
     * Gets the value of the subOrgID property.
     * 
     * @return
     *     possible object is
     *     {@link OasStringType }
     *     
     */
    public OasStringType getSubOrgID() {
        return subOrgID;
    }

    /**
     * Sets the value of the subOrgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasStringType }
     *     
     */
    public void setSubOrgID(OasStringType value) {
        this.subOrgID = value;
    }

    /**
     * Gets the value of the fusfExemptFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getFUSFExemptFlag() {
        return fusfExemptFlag;
    }

    /**
     * Sets the value of the fusfExemptFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setFUSFExemptFlag(YesNoType value) {
        this.fusfExemptFlag = value;
    }

    /**
     * Gets the value of the globalSIMCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalSIMCard() {
        return globalSIMCard;
    }

    /**
     * Sets the value of the globalSIMCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalSIMCard(String value) {
        this.globalSIMCard = value;
    }

    /**
     * Gets the value of the serviceTypeChange property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getServiceTypeChange() {
        return serviceTypeChange;
    }

    /**
     * Sets the value of the serviceTypeChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setServiceTypeChange(YesNoType value) {
        this.serviceTypeChange = value;
    }

    /**
     * Gets the value of the newRatePlan property.
     * 
     * @return
     *     possible object is
     *     {@link RatePlanType }
     *     
     */
    public RatePlanType getNewRatePlan() {
        return newRatePlan;
    }

    /**
     * Sets the value of the newRatePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatePlanType }
     *     
     */
    public void setNewRatePlan(RatePlanType value) {
        this.newRatePlan = value;
    }

    /**
     * Gets the value of the oldRatePlan property.
     * 
     * @return
     *     possible object is
     *     {@link RatePlanType }
     *     
     */
    public RatePlanType getOldRatePlan() {
        return oldRatePlan;
    }

    /**
     * Sets the value of the oldRatePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatePlanType }
     *     
     */
    public void setOldRatePlan(RatePlanType value) {
        this.oldRatePlan = value;
    }

}
