//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 06:47:32 PM CST 
//


package com.budgetprepay.verizon.rss.pojos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for updatePortInType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updatePortInType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.verizonwireless.com/oas}resellerSubOrderBaseType">
 *       &lt;sequence>
 *         &lt;element name="originalRefNumber" type="{http://www.verizonwireless.com/oas}referenceNumberType"/>
 *         &lt;element name="mdn" type="{http://www.verizonwireless.com/oas}mdnType" minOccurs="0"/>
 *         &lt;element name="updateType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="MODIFY"/>
 *               &lt;enumeration value="CANCEL"/>
 *               &lt;enumeration value="ACTIVATE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="deviceId" type="{http://www.verizonwireless.com/oas}deviceIdType" minOccurs="0"/>
 *           &lt;element name="desiredDueDate" type="{http://www.verizonwireless.com/oas}desiredDueDateType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="remark" type="{http://www.verizonwireless.com/oas}oasString160Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updatePortInType", propOrder = {
    "originalRefNumber",
    "mdn",
    "updateType",
    "deviceId",
    "desiredDueDate",
    "remark"
})
public class UpdatePortInType
    extends ResellerSubOrderBaseType
{

    @XmlElement(required = true)
    protected ReferenceNumberType originalRefNumber;
    protected MdnType mdn;
    @XmlElement(required = true)
    protected String updateType;
    protected String deviceId;
    protected XMLGregorianCalendar desiredDueDate;
    protected OasString160Type remark;

    /**
     * Gets the value of the originalRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberType }
     *     
     */
    public ReferenceNumberType getOriginalRefNumber() {
        return originalRefNumber;
    }

    /**
     * Sets the value of the originalRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberType }
     *     
     */
    public void setOriginalRefNumber(ReferenceNumberType value) {
        this.originalRefNumber = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link MdnType }
     *     
     */
    public MdnType getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MdnType }
     *     
     */
    public void setMdn(MdnType value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the updateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * Sets the value of the updateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateType(String value) {
        this.updateType = value;
    }

    /**
     * Gets the value of the deviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the desiredDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDesiredDueDate() {
        return desiredDueDate;
    }

    /**
     * Sets the value of the desiredDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDesiredDueDate(XMLGregorianCalendar value) {
        this.desiredDueDate = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link OasString160Type }
     *     
     */
    public OasString160Type getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasString160Type }
     *     
     */
    public void setRemark(OasString160Type value) {
        this.remark = value;
    }

}
