//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 10:52:28 AM CDT 
//


package com.budgetprepay.webservice.pojos.plintron;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serviceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MOCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MORoamingCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTRoamingCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MOSMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTSMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MORoamingSMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTRoamingSMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IVR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="USSD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VMS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SMSTopup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MobileHomeAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MOVideoCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTVideoCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MORoamingVideoCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTRoamingVideoCall" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MCA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CRBT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MOData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MORoamData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviceInfoType", propOrder = {
    "moCall",
    "mtCall",
    "moRoamingCall",
    "mtRoamingCall",
    "mosms",
    "mtsms",
    "moRoamingSMS",
    "mtRoamingSMS",
    "ivr",
    "ussd",
    "vms",
    "smsTopup",
    "mobileHomeAccount",
    "moVideoCall",
    "mtVideoCall",
    "moRoamingVideoCall",
    "mtRoamingVideoCall",
    "mca",
    "crbt",
    "moData",
    "moRoamData",
    "cbs"
})
public class ServiceInfoType {

    @XmlElement(name = "MOCall")
    protected String moCall;
    @XmlElement(name = "MTCall")
    protected String mtCall;
    @XmlElement(name = "MORoamingCall")
    protected String moRoamingCall;
    @XmlElement(name = "MTRoamingCall")
    protected String mtRoamingCall;
    @XmlElement(name = "MOSMS")
    protected String mosms;
    @XmlElement(name = "MTSMS")
    protected String mtsms;
    @XmlElement(name = "MORoamingSMS")
    protected String moRoamingSMS;
    @XmlElement(name = "MTRoamingSMS")
    protected String mtRoamingSMS;
    @XmlElement(name = "IVR")
    protected String ivr;
    @XmlElement(name = "USSD")
    protected String ussd;
    @XmlElement(name = "VMS")
    protected String vms;
    @XmlElement(name = "SMSTopup")
    protected String smsTopup;
    @XmlElement(name = "MobileHomeAccount")
    protected String mobileHomeAccount;
    @XmlElement(name = "MOVideoCall")
    protected String moVideoCall;
    @XmlElement(name = "MTVideoCall")
    protected String mtVideoCall;
    @XmlElement(name = "MORoamingVideoCall")
    protected String moRoamingVideoCall;
    @XmlElement(name = "MTRoamingVideoCall")
    protected String mtRoamingVideoCall;
    @XmlElement(name = "MCA")
    protected String mca;
    @XmlElement(name = "CRBT")
    protected String crbt;
    @XmlElement(name = "MOData")
    protected String moData;
    @XmlElement(name = "MORoamData")
    protected String moRoamData;
    @XmlElement(name = "CBS")
    protected String cbs;

    /**
     * Gets the value of the moCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOCall() {
        return moCall;
    }

    /**
     * Sets the value of the moCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOCall(String value) {
        this.moCall = value;
    }

    /**
     * Gets the value of the mtCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTCall() {
        return mtCall;
    }

    /**
     * Sets the value of the mtCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTCall(String value) {
        this.mtCall = value;
    }

    /**
     * Gets the value of the moRoamingCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMORoamingCall() {
        return moRoamingCall;
    }

    /**
     * Sets the value of the moRoamingCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMORoamingCall(String value) {
        this.moRoamingCall = value;
    }

    /**
     * Gets the value of the mtRoamingCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTRoamingCall() {
        return mtRoamingCall;
    }

    /**
     * Sets the value of the mtRoamingCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTRoamingCall(String value) {
        this.mtRoamingCall = value;
    }

    /**
     * Gets the value of the mosms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOSMS() {
        return mosms;
    }

    /**
     * Sets the value of the mosms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOSMS(String value) {
        this.mosms = value;
    }

    /**
     * Gets the value of the mtsms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTSMS() {
        return mtsms;
    }

    /**
     * Sets the value of the mtsms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTSMS(String value) {
        this.mtsms = value;
    }

    /**
     * Gets the value of the moRoamingSMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMORoamingSMS() {
        return moRoamingSMS;
    }

    /**
     * Sets the value of the moRoamingSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMORoamingSMS(String value) {
        this.moRoamingSMS = value;
    }

    /**
     * Gets the value of the mtRoamingSMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTRoamingSMS() {
        return mtRoamingSMS;
    }

    /**
     * Sets the value of the mtRoamingSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTRoamingSMS(String value) {
        this.mtRoamingSMS = value;
    }

    /**
     * Gets the value of the ivr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIVR() {
        return ivr;
    }

    /**
     * Sets the value of the ivr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIVR(String value) {
        this.ivr = value;
    }

    /**
     * Gets the value of the ussd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSSD() {
        return ussd;
    }

    /**
     * Sets the value of the ussd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSSD(String value) {
        this.ussd = value;
    }

    /**
     * Gets the value of the vms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVMS() {
        return vms;
    }

    /**
     * Sets the value of the vms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVMS(String value) {
        this.vms = value;
    }

    /**
     * Gets the value of the smsTopup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMSTopup() {
        return smsTopup;
    }

    /**
     * Sets the value of the smsTopup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMSTopup(String value) {
        this.smsTopup = value;
    }

    /**
     * Gets the value of the mobileHomeAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileHomeAccount() {
        return mobileHomeAccount;
    }

    /**
     * Sets the value of the mobileHomeAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileHomeAccount(String value) {
        this.mobileHomeAccount = value;
    }

    /**
     * Gets the value of the moVideoCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVideoCall() {
        return moVideoCall;
    }

    /**
     * Sets the value of the moVideoCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVideoCall(String value) {
        this.moVideoCall = value;
    }

    /**
     * Gets the value of the mtVideoCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTVideoCall() {
        return mtVideoCall;
    }

    /**
     * Sets the value of the mtVideoCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTVideoCall(String value) {
        this.mtVideoCall = value;
    }

    /**
     * Gets the value of the moRoamingVideoCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMORoamingVideoCall() {
        return moRoamingVideoCall;
    }

    /**
     * Sets the value of the moRoamingVideoCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMORoamingVideoCall(String value) {
        this.moRoamingVideoCall = value;
    }

    /**
     * Gets the value of the mtRoamingVideoCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMTRoamingVideoCall() {
        return mtRoamingVideoCall;
    }

    /**
     * Sets the value of the mtRoamingVideoCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMTRoamingVideoCall(String value) {
        this.mtRoamingVideoCall = value;
    }

    /**
     * Gets the value of the mca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCA() {
        return mca;
    }

    /**
     * Sets the value of the mca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCA(String value) {
        this.mca = value;
    }

    /**
     * Gets the value of the crbt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRBT() {
        return crbt;
    }

    /**
     * Sets the value of the crbt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRBT(String value) {
        this.crbt = value;
    }

    /**
     * Gets the value of the moData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOData() {
        return moData;
    }

    /**
     * Sets the value of the moData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOData(String value) {
        this.moData = value;
    }

    /**
     * Gets the value of the moRoamData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMORoamData() {
        return moRoamData;
    }

    /**
     * Sets the value of the moRoamData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMORoamData(String value) {
        this.moRoamData = value;
    }

    /**
     * Gets the value of the cbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBS() {
        return cbs;
    }

    /**
     * Sets the value of the cbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBS(String value) {
        this.cbs = value;
    }

}
