//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:13:08 PM CDT 
//


package com.budgetprepay.webservice.client.verizon.rss.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lnpPersonNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lnpPersonNameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="first" type="{http://www.verizonwireless.com/oas}personNameType"/>
 *         &lt;element name="middleInitial" type="{http://www.verizonwireless.com/oas}oasSingleCharacterType" minOccurs="0"/>
 *         &lt;element name="last" type="{http://www.verizonwireless.com/oas}personNameType"/>
 *         &lt;element name="suffix" type="{http://www.verizonwireless.com/oas}oasString10Type" minOccurs="0"/>
 *         &lt;element name="prefix" type="{http://www.verizonwireless.com/oas}oasString10Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lnpPersonNameType", propOrder = {
    "first",
    "middleInitial",
    "last",
    "suffix",
    "prefix"
})
public class LnpPersonNameType {

    @XmlElement(required = true)
    protected PersonNameType first;
    protected OasSingleCharacterType middleInitial;
    @XmlElement(required = true)
    protected PersonNameType last;
    protected OasString10Type suffix;
    protected OasString10Type prefix;

    /**
     * Gets the value of the first property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameType }
     *     
     */
    public PersonNameType getFirst() {
        return first;
    }

    /**
     * Sets the value of the first property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameType }
     *     
     */
    public void setFirst(PersonNameType value) {
        this.first = value;
    }

    /**
     * Gets the value of the middleInitial property.
     * 
     * @return
     *     possible object is
     *     {@link OasSingleCharacterType }
     *     
     */
    public OasSingleCharacterType getMiddleInitial() {
        return middleInitial;
    }

    /**
     * Sets the value of the middleInitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasSingleCharacterType }
     *     
     */
    public void setMiddleInitial(OasSingleCharacterType value) {
        this.middleInitial = value;
    }

    /**
     * Gets the value of the last property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameType }
     *     
     */
    public PersonNameType getLast() {
        return last;
    }

    /**
     * Sets the value of the last property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameType }
     *     
     */
    public void setLast(PersonNameType value) {
        this.last = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link OasString10Type }
     *     
     */
    public OasString10Type getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasString10Type }
     *     
     */
    public void setSuffix(OasString10Type value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link OasString10Type }
     *     
     */
    public OasString10Type getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link OasString10Type }
     *     
     */
    public void setPrefix(OasString10Type value) {
        this.prefix = value;
    }

}
