//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:13:08 PM CDT 
//


package com.budgetprepay.webservice.client.verizon.rss.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lnpUpdateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lnpUpdateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lnpName" type="{http://www.verizonwireless.com/oas}lnpNameType"/>
 *         &lt;element name="address" type="{http://www.verizonwireless.com/oas}lnpAddressType"/>
 *         &lt;element name="directionalIndicator" type="{http://www.verizonwireless.com/oas}directionalIndicatorType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="ssnOrTaxId" type="{http://www.verizonwireless.com/oas}ssnOrTaxIdType"/>
 *             &lt;element name="ospAccountNo" type="{http://www.verizonwireless.com/oas}ospAccountNoType" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="ospAccountNo" type="{http://www.verizonwireless.com/oas}ospAccountNoType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="pin" type="{http://www.verizonwireless.com/oas}pinType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lnpUpdateType", propOrder = {
    "content"
})
public class LnpUpdateType {

    @XmlElementRefs({
        @XmlElementRef(name = "lnpName", namespace = "http://www.verizonwireless.com/oas", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ospAccountNo", namespace = "http://www.verizonwireless.com/oas", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ssnOrTaxId", namespace = "http://www.verizonwireless.com/oas", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pin", namespace = "http://www.verizonwireless.com/oas", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "address", namespace = "http://www.verizonwireless.com/oas", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "directionalIndicator", namespace = "http://www.verizonwireless.com/oas", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "OspAccountNo" is used by two different parts of a schema. See: 
     * line 457 of file:/C:/Users/steve.thomas/workspace/MVNO/src/reseller.38.0.xsd
     * line 454 of file:/C:/Users/steve.thomas/workspace/MVNO/src/reseller.38.0.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SsnOrTaxIdType }{@code >}
     * {@link JAXBElement }{@code <}{@link OspAccountNoType }{@code >}
     * {@link JAXBElement }{@code <}{@link PinType }{@code >}
     * {@link JAXBElement }{@code <}{@link LnpAddressType }{@code >}
     * {@link JAXBElement }{@code <}{@link LnpNameType }{@code >}
     * {@link JAXBElement }{@code <}{@link DirectionalIndicatorType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
