//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:23:41 PM CDT 
//


package com.budgetprepay.webservice.pojos.verizon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ChangeESNRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeESNRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageHeader" type="{http://www.budgetprepay.com/MVNO/Verizon}messageHeaderType"/>
 *         &lt;element name="mdn" type="{http://www.budgetprepay.com/MVNO/Verizon}phoneType"/>
 *         &lt;choice>
 *           &lt;element name="esnWithOldEsn">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>esnType">
 *                   &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}esnType" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="esnWithOldMeid">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>esnType">
 *                   &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}meidType" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="meidWithOldEsn">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>meidType">
 *                   &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}esnType" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="meidWithOldMeid">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>meidType">
 *                   &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}meidType" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeESNRequest", propOrder = {
    "messageHeader",
    "mdn",
    "esnWithOldEsn",
    "esnWithOldMeid",
    "meidWithOldEsn",
    "meidWithOldMeid"
})
public class ChangeESNRequest {

    @XmlElement(required = true)
    protected MessageHeaderType messageHeader;
    @XmlElement(required = true)
    protected String mdn;
    protected ChangeESNRequest.EsnWithOldEsn esnWithOldEsn;
    protected ChangeESNRequest.EsnWithOldMeid esnWithOldMeid;
    protected ChangeESNRequest.MeidWithOldEsn meidWithOldEsn;
    protected ChangeESNRequest.MeidWithOldMeid meidWithOldMeid;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderType }
     *     
     */
    public MessageHeaderType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderType }
     *     
     */
    public void setMessageHeader(MessageHeaderType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the esnWithOldEsn property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeESNRequest.EsnWithOldEsn }
     *     
     */
    public ChangeESNRequest.EsnWithOldEsn getEsnWithOldEsn() {
        return esnWithOldEsn;
    }

    /**
     * Sets the value of the esnWithOldEsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeESNRequest.EsnWithOldEsn }
     *     
     */
    public void setEsnWithOldEsn(ChangeESNRequest.EsnWithOldEsn value) {
        this.esnWithOldEsn = value;
    }

    /**
     * Gets the value of the esnWithOldMeid property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeESNRequest.EsnWithOldMeid }
     *     
     */
    public ChangeESNRequest.EsnWithOldMeid getEsnWithOldMeid() {
        return esnWithOldMeid;
    }

    /**
     * Sets the value of the esnWithOldMeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeESNRequest.EsnWithOldMeid }
     *     
     */
    public void setEsnWithOldMeid(ChangeESNRequest.EsnWithOldMeid value) {
        this.esnWithOldMeid = value;
    }

    /**
     * Gets the value of the meidWithOldEsn property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeESNRequest.MeidWithOldEsn }
     *     
     */
    public ChangeESNRequest.MeidWithOldEsn getMeidWithOldEsn() {
        return meidWithOldEsn;
    }

    /**
     * Sets the value of the meidWithOldEsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeESNRequest.MeidWithOldEsn }
     *     
     */
    public void setMeidWithOldEsn(ChangeESNRequest.MeidWithOldEsn value) {
        this.meidWithOldEsn = value;
    }

    /**
     * Gets the value of the meidWithOldMeid property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeESNRequest.MeidWithOldMeid }
     *     
     */
    public ChangeESNRequest.MeidWithOldMeid getMeidWithOldMeid() {
        return meidWithOldMeid;
    }

    /**
     * Sets the value of the meidWithOldMeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeESNRequest.MeidWithOldMeid }
     *     
     */
    public void setMeidWithOldMeid(ChangeESNRequest.MeidWithOldMeid value) {
        this.meidWithOldMeid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>esnType">
     *       &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}esnType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EsnWithOldEsn {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "old")
        protected String old;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the old property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOld() {
            return old;
        }

        /**
         * Sets the value of the old property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOld(String value) {
            this.old = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>esnType">
     *       &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}meidType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EsnWithOldMeid {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "old")
        protected String old;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the old property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOld() {
            return old;
        }

        /**
         * Sets the value of the old property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOld(String value) {
            this.old = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>meidType">
     *       &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}esnType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MeidWithOldEsn {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "old")
        protected String old;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the old property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOld() {
            return old;
        }

        /**
         * Sets the value of the old property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOld(String value) {
            this.old = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.budgetprepay.com/MVNO/Verizon>meidType">
     *       &lt;attribute name="old" type="{http://www.budgetprepay.com/MVNO/Verizon}meidType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MeidWithOldMeid {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "old")
        protected String old;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the old property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOld() {
            return old;
        }

        /**
         * Sets the value of the old property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOld(String value) {
            this.old = value;
        }

    }

}
