//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:23:41 PM CDT 
//


package com.budgetprepay.webservice.pojos.verizon;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *     Note: If an MDN is not supplied then nextAvailableMDN must be supplied.
 *     In this case we will obtain the MDN from the Enterprise Number
 *     Inventory pool using the supplied fields in the nextAvailableMDNType.
 *     If the MPNPoolName tag is given in the xml, the feature element for MPN static IP 
 *     or MPN dynamic IP (MPNSIP or MPNDIP) should be included in the features section. 
 *    
 * 
 * <p>Java class for DeviceActivationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeviceActivationRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageHeader" type="{http://www.budgetprepay.com/MVNO/Verizon}messageHeaderType"/>
 *         &lt;element name="feature" type="{http://www.budgetprepay.com/MVNO/Verizon}featureType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="mdn" type="{http://www.budgetprepay.com/MVNO/Verizon}phoneType"/>
 *           &lt;element name="nextAvailableMDN" type="{http://www.budgetprepay.com/MVNO/Verizon}nextAvailableMDNType"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="meid" type="{http://www.budgetprepay.com/MVNO/Verizon}meidType"/>
 *           &lt;element name="esn" type="{http://www.budgetprepay.com/MVNO/Verizon}esnType"/>
 *         &lt;/choice>
 *         &lt;element name="mobileIPAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mpnPoolName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subOrgId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceActivationRequest", propOrder = {
    "messageHeader",
    "feature",
    "mdn",
    "nextAvailableMDN",
    "meid",
    "esn",
    "mobileIPAddress",
    "mpnPoolName",
    "subOrgId"
})
public class DeviceActivationRequest {

    @XmlElement(required = true)
    protected MessageHeaderType messageHeader;
    protected List<FeatureType> feature;
    protected String mdn;
    protected NextAvailableMDNType nextAvailableMDN;
    protected String meid;
    protected String esn;
    protected String mobileIPAddress;
    protected String mpnPoolName;
    protected String subOrgId;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderType }
     *     
     */
    public MessageHeaderType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderType }
     *     
     */
    public void setMessageHeader(MessageHeaderType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the feature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType }
     * 
     * 
     */
    public List<FeatureType> getFeature() {
        if (feature == null) {
            feature = new ArrayList<FeatureType>();
        }
        return this.feature;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the nextAvailableMDN property.
     * 
     * @return
     *     possible object is
     *     {@link NextAvailableMDNType }
     *     
     */
    public NextAvailableMDNType getNextAvailableMDN() {
        return nextAvailableMDN;
    }

    /**
     * Sets the value of the nextAvailableMDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link NextAvailableMDNType }
     *     
     */
    public void setNextAvailableMDN(NextAvailableMDNType value) {
        this.nextAvailableMDN = value;
    }

    /**
     * Gets the value of the meid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeid() {
        return meid;
    }

    /**
     * Sets the value of the meid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeid(String value) {
        this.meid = value;
    }

    /**
     * Gets the value of the esn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsn() {
        return esn;
    }

    /**
     * Sets the value of the esn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsn(String value) {
        this.esn = value;
    }

    /**
     * Gets the value of the mobileIPAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileIPAddress() {
        return mobileIPAddress;
    }

    /**
     * Sets the value of the mobileIPAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileIPAddress(String value) {
        this.mobileIPAddress = value;
    }

    /**
     * Gets the value of the mpnPoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpnPoolName() {
        return mpnPoolName;
    }

    /**
     * Sets the value of the mpnPoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpnPoolName(String value) {
        this.mpnPoolName = value;
    }

    /**
     * Gets the value of the subOrgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubOrgId() {
        return subOrgId;
    }

    /**
     * Sets the value of the subOrgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubOrgId(String value) {
        this.subOrgId = value;
    }

}
