//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:23:41 PM CDT 
//


package com.budgetprepay.webservice.pojos.verizon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordArrayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordArrayType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rowID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="callStartTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eventLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eventResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preEventBal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postEventBal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="callDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="callCost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="origDialedDigits" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tarriffPlanCOSP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isRevertable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="internationalRoamin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdrType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordArrayType", propOrder = {
    "rowID",
    "mdn",
    "callStartTime",
    "providerID",
    "eventLabel",
    "eventResult",
    "preEventBal",
    "postEventBal",
    "callDuration",
    "callCost",
    "origDialedDigits",
    "cos",
    "tarriffPlanCOSP",
    "isRevertable",
    "internationalRoamin",
    "cdrType"
})
public class RecordArrayType {

    protected String rowID;
    protected String mdn;
    protected String callStartTime;
    protected String providerID;
    protected String eventLabel;
    protected String eventResult;
    protected String preEventBal;
    protected String postEventBal;
    protected String callDuration;
    protected String callCost;
    protected String origDialedDigits;
    protected String cos;
    protected String tarriffPlanCOSP;
    protected String isRevertable;
    protected String internationalRoamin;
    protected String cdrType;

    /**
     * Gets the value of the rowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowID() {
        return rowID;
    }

    /**
     * Sets the value of the rowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowID(String value) {
        this.rowID = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the callStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallStartTime() {
        return callStartTime;
    }

    /**
     * Sets the value of the callStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallStartTime(String value) {
        this.callStartTime = value;
    }

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderID(String value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the eventLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventLabel() {
        return eventLabel;
    }

    /**
     * Sets the value of the eventLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventLabel(String value) {
        this.eventLabel = value;
    }

    /**
     * Gets the value of the eventResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventResult() {
        return eventResult;
    }

    /**
     * Sets the value of the eventResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventResult(String value) {
        this.eventResult = value;
    }

    /**
     * Gets the value of the preEventBal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreEventBal() {
        return preEventBal;
    }

    /**
     * Sets the value of the preEventBal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreEventBal(String value) {
        this.preEventBal = value;
    }

    /**
     * Gets the value of the postEventBal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostEventBal() {
        return postEventBal;
    }

    /**
     * Sets the value of the postEventBal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostEventBal(String value) {
        this.postEventBal = value;
    }

    /**
     * Gets the value of the callDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallDuration() {
        return callDuration;
    }

    /**
     * Sets the value of the callDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallDuration(String value) {
        this.callDuration = value;
    }

    /**
     * Gets the value of the callCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallCost() {
        return callCost;
    }

    /**
     * Sets the value of the callCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallCost(String value) {
        this.callCost = value;
    }

    /**
     * Gets the value of the origDialedDigits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigDialedDigits() {
        return origDialedDigits;
    }

    /**
     * Sets the value of the origDialedDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigDialedDigits(String value) {
        this.origDialedDigits = value;
    }

    /**
     * Gets the value of the cos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCos() {
        return cos;
    }

    /**
     * Sets the value of the cos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCos(String value) {
        this.cos = value;
    }

    /**
     * Gets the value of the tarriffPlanCOSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarriffPlanCOSP() {
        return tarriffPlanCOSP;
    }

    /**
     * Sets the value of the tarriffPlanCOSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarriffPlanCOSP(String value) {
        this.tarriffPlanCOSP = value;
    }

    /**
     * Gets the value of the isRevertable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsRevertable() {
        return isRevertable;
    }

    /**
     * Sets the value of the isRevertable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsRevertable(String value) {
        this.isRevertable = value;
    }

    /**
     * Gets the value of the internationalRoamin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRoamin() {
        return internationalRoamin;
    }

    /**
     * Sets the value of the internationalRoamin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRoamin(String value) {
        this.internationalRoamin = value;
    }

    /**
     * Gets the value of the cdrType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdrType() {
        return cdrType;
    }

    /**
     * Sets the value of the cdrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdrType(String value) {
        this.cdrType = value;
    }

}
