//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 06:23:41 PM CDT 
//


package com.budgetprepay.webservice.pojos.verizon;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchPINBatchResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchPINBatchResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="returnMessage" type="{http://www.budgetprepay.com/MVNO/Verizon}returnMessageType"/>
 *         &lt;element name="transactionContext" type="{http://www.budgetprepay.com/MVNO/Verizon}transactionContextType" minOccurs="0"/>
 *         &lt;element name="batchAttributes" type="{http://www.budgetprepay.com/MVNO/Verizon}batchAttributesType" minOccurs="0"/>
 *         &lt;element name="pinAttributes" type="{http://www.budgetprepay.com/MVNO/Verizon}pinAttributesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchPINBatchResponse", propOrder = {
    "returnMessage",
    "transactionContext",
    "batchAttributes",
    "pinAttributes"
})
public class SearchPINBatchResponse {

    @XmlElement(required = true)
    protected ReturnMessageType returnMessage;
    protected TransactionContextType transactionContext;
    protected BatchAttributesType batchAttributes;
    protected List<PinAttributesType> pinAttributes;

    /**
     * Gets the value of the returnMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnMessageType }
     *     
     */
    public ReturnMessageType getReturnMessage() {
        return returnMessage;
    }

    /**
     * Sets the value of the returnMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnMessageType }
     *     
     */
    public void setReturnMessage(ReturnMessageType value) {
        this.returnMessage = value;
    }

    /**
     * Gets the value of the transactionContext property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionContextType }
     *     
     */
    public TransactionContextType getTransactionContext() {
        return transactionContext;
    }

    /**
     * Sets the value of the transactionContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionContextType }
     *     
     */
    public void setTransactionContext(TransactionContextType value) {
        this.transactionContext = value;
    }

    /**
     * Gets the value of the batchAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link BatchAttributesType }
     *     
     */
    public BatchAttributesType getBatchAttributes() {
        return batchAttributes;
    }

    /**
     * Sets the value of the batchAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchAttributesType }
     *     
     */
    public void setBatchAttributes(BatchAttributesType value) {
        this.batchAttributes = value;
    }

    /**
     * Gets the value of the pinAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pinAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPinAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PinAttributesType }
     * 
     * 
     */
    public List<PinAttributesType> getPinAttributes() {
        if (pinAttributes == null) {
            pinAttributes = new ArrayList<PinAttributesType>();
        }
        return this.pinAttributes;
    }

}
